# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z2_v1.0.xdc/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/demo/demo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo || ORIG_REF_NAME==demo} -quiet] -quiet

# IP: bd/demo/ip/demo_number_capture_4bit_0_0/demo_number_capture_4bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_number_capture_4bit_0_0 || ORIG_REF_NAME==demo_number_capture_4bit_0_0} -quiet] -quiet

# IP: bd/demo/ip/demo_AsciiCharsMem_0_0/demo_AsciiCharsMem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_AsciiCharsMem_0_0 || ORIG_REF_NAME==demo_AsciiCharsMem_0_0} -quiet] -quiet

# IP: bd/demo/ip/demo_VGA_timings_0_0/demo_VGA_timings_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_VGA_timings_0_0 || ORIG_REF_NAME==demo_VGA_timings_0_0} -quiet] -quiet

# IP: bd/demo/ip/demo_VGA_pattern_0_0/demo_VGA_pattern_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_VGA_pattern_0_0 || ORIG_REF_NAME==demo_VGA_pattern_0_0} -quiet] -quiet

# IP: bd/demo/ip/demo_ScreenBufferMem_0_0/demo_ScreenBufferMem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_ScreenBufferMem_0_0 || ORIG_REF_NAME==demo_ScreenBufferMem_0_0} -quiet] -quiet

# IP: bd/demo/ip/demo_clk_wiz_0_0/demo_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_clk_wiz_0_0 || ORIG_REF_NAME==demo_clk_wiz_0_0} -quiet] -quiet

# IP: bd/demo/ip/demo_Debounce_Switch_0_0/demo_Debounce_Switch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_Debounce_Switch_0_0 || ORIG_REF_NAME==demo_Debounce_Switch_0_0} -quiet] -quiet

# IP: bd/demo/ip/demo_Debounce_Switch_1_0/demo_Debounce_Switch_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_Debounce_Switch_1_0 || ORIG_REF_NAME==demo_Debounce_Switch_1_0} -quiet] -quiet

# IP: bd/demo/ip/demo_Debounce_Switch_1_1/demo_Debounce_Switch_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_Debounce_Switch_1_1 || ORIG_REF_NAME==demo_Debounce_Switch_1_1} -quiet] -quiet

# IP: bd/demo/ip/demo_Debounce_Switch_2_0/demo_Debounce_Switch_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_Debounce_Switch_2_0 || ORIG_REF_NAME==demo_Debounce_Switch_2_0} -quiet] -quiet

# XDC: bd/demo/demo_ooc.xdc
